version: "3.8"

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/eureka-server:latest
    restart: always
    ports:
      - "8761:8761"
    networks:
      - backend-network

  user-service:
    build:
      context: ./user-service
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/user-service:latest
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - user_db
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_db:5432/ShopSwiftly
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-network

  user_db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
