name: Java CI/CD Pipeline with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java environment
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      
      - name: Build with Maven
        run: mvn clean install
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push with Docker Compose
        run: |
          docker-compose build
          docker-compose push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MYSQL_DATABASE_PRODUCTS: ${{ secrets.MYSQL_DATABASE_PRODUCTS }}
          MYSQL_DATABASE_TRANSACTIONS: ${{ secrets.MYSQL_DATABASE_TRANSACTIONS }}
          MYSQL_DATABASE_USERS: ${{ secrets.MYSQL_DATABASE_USERS }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
